development: &DEFAULT
  pid: "2088311153957205"
  PCpid: "2088311255794898"
  email: bike@bestapp.us
  PC_email: danchedianying@163.com
  api_url: "https://openapi.alipay.com/gateway.do"
  mapi_url: "https://mapi.alipay.com/gateway.do"
  wap_api_url: "http://wappaygw.alipay.com/service/rest.htm"
  refund_url: "http://bike.app.cm/alipay/alipay_refund_notify"
  wireless_refund_url: "http://bike.app.cm/alipay/alipay_wireless_refund_notify"
  notify_url: "http://bike.app.cm/api/v1/mobile_alipay_notify"
  md5_key: "9fv6vb030s043q6bb267o2qcdkypaman"
  PC_md5_key: "4iicr5g2shsm1co6uub7v4ruav1nyy5e"
  alipay_rsa_pub_key: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCnxj/9qwVfgoUh/y2W89L6BkRAFljhNhgPdyPuBV64bfQNN1PjbCzkIM6qRdKBoLPXmKKMiFYnkd6rAoprih3/PrQEB/VsW8OoM8fxn67UDYuyBTqA23MML9q1+ilIZwBC2AQ2UBVOrFXfFl75p6/B5KsiNG9zpgmLCUYuLkxpLQIDAQAB"
  rsa_pub_key: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCsR5XdmvDyPXXvUV7ZEchdG12GvQY2qZhzacWPvr2IphFsvvdIeqsy87V4Wli6fmRdzMv8IKHW/LPr6Pb9rkysgDYFuxWob2YsmaN7CiJZj50fmJ+cx5Rex69NXEaNDKF2hHm5zd6ZQH8sMJDQhrRdjyGFVtIV1Cg86Du6c1QPxwIDAQAB"
  sandbox_pcks8_key: "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMiAec6fsssguUoRN3oEVEnQaqBLZjeafXAxCbKH3MTJaXPmnXOtqFFqFtcB8J9KqyFI1+o6YBDNIdFWMKqOwDDWPKqtdo90oGav3QMikjGYjIpe/gYYCQ/In/oVMVj326GmKrSpp0P+5LNCx59ajRpO8//rnOLd6h/tNxnfahanAgMBAAECgYEAusouMFfJGsIWvLEDbPIhkE7RNxpnVP/hQqb8sM0v2EkHrAk5wG4VNBvQwWe2QsAuY6jYNgdCPgTNL5fLaOnqkyy8IobrddtT/t3vDX96NNjHP4xfhnMbpGjkKZuljWKduK2FAh83eegrSH48TuWS87LjeZNHhr5x4C0KHeBTYekCQQD5cyrFuKua6GNG0dTj5gA67R9jcmtcDWgSsuIXS0lzUeGxZC4y/y/76l6S7jBYuGkz/x2mJaZ/b3MxxcGQ01YNAkEAzcRGLTXgTMg33UOR13oqXiV9cQbraHR/aPmS8kZxkJNYows3K3umNVjLhFGusstmLIY2pIpPNUOho1YYatPGgwJBANq8vnj64p/Hv6ZOQZxGB1WksK2Hm9TwfJ5I9jDu982Ds6DV9B0L4IvKjHvTGdnye234+4rB4SpGFIFEo+PXLdECQBiOPMW2cT8YgboxDx2E4bt8g9zSM5Oym2Xeqs+o4nKbcu96LipNRkeFgjwXN1708QuNNMYsD0nO+WIxqxZMkZsCQHtS+Jj/LCnQZgLKxXZAllxqSTlBln2YnBgk6HqHLp8Eknx2rUXhoxE1vD9tNmom6PiaZlQyukrQkp5GOMWDMkU="
  sandbox_rsa_pub_key: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDIgHnOn7LLILlKETd6BFRJ0GqgS2Y3mn1wMQmyh9zEyWlz5p1zrahRahbXAfCfSqshSNfqOmAQzSHRVjCqjsAw1jyqrXaPdKBmr90DIpIxmIyKXv4GGAkPyJ/6FTFY99uhpiq0qadD/uSzQsefWo0aTvP/65zi3eof7TcZ32oWpwIDAQAB"
  sandbox_app_id: "2013120600052423"
  sandbox_pid: "2088101131243925"
  alipublic_app_id: "2013121000002321"
  mobile_app_id: "2014031700004193"
  alipass_app_id: "2014031700004193"

test:
  <<: *DEFAULT

production:
  <<: *DEFAULT

staging:
  <<: *DEFAULT
