:concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - default
  - elasticsearch
  - convert_audio
  - umeng_msg
  - fetch_image
  - update_viagogo_event
  - update_viagogo_stadium_map
staging:
  :concurrency: 25
production:
  :concurrency: 10
