:concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - default
  - elasticsearch
  - convert_audio
  - umeng_msg
staging:
  :concurrency: 25
production:
  :concurrency: 10
