pid: "example_pid"
PCpid: "example_PCid"
email: bike@bestapp.us
PC_email: danchedianying@163.com
api_url: "https://openapi.alipay.com/gateway.do"
mapi_url: "https://mapi.alipay.com/gateway.do"
wap_api_url: "http://wappaygw.alipay.com/service/rest.htm"
wireless_refund_url: "http://hoishow.dan-che.com/api/v1/alipay/wireless_refund_notify"
notify_url: "http://hoishow.dan-che.com/api/v1/alipay/nofity"
md5_key: "example_md5_key"
PC_md5_key: "example_PC_md5_key"
alipay_rsa_pub_key: "example_alipay_rsa_pub_key"
rsa_pub_key: "example_alipay_rsa_pub_key"
sandbox_pcks8_key: "example_sandbox_pcks8_key"
sandbox_rsa_pub_key: "example_sandbox_rsa_pub_key"
sandbox_app_id: "example_sandbox_app_id3"
sandbox_pid: "example_sandbox_pid"
alipublic_app_id: "example_alipublic_app_id"
mobile_app_id: "example_mobile_app_id"
alipass_app_id: "example_alipass_app_id"
